apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  namespace: [student-name]
  labels:
    type: local
spec:
  storageClassName: database
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/var/lib/mysql/[student-name]"